name: Trigger milvus.io production build

on:
  repository_dispatch:
    types: prod-deploy
  push:
    paths-ignore:
      - "preview/**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      # - name: Stats Docs Words
      #   env:
      #     MSERVICE_URL: ${{secrets.MSERVICE_URL}}
      #   run: |
      #     mv word-count.md word-count.js
      #     yarn
      #     node word-count.js

      - name: Trigger milvus.io
        run: |
          curl -XPOST -H "Authorization: Bearer ${{secrets.GH_TOKEN}}" https://api.github.com/repos/milvus-io/milvus.io/dispatches -d '{"event_type": "prod-deploy"}'
